VK-Lab/mlem-dashboard

- package.json
- src/enums/index.ts
- src/enums/loginType.enum.ts
- src/hooks/useOnLogin.ts
- src/layouts/DashboardLayout/AdminTopbar/index.tsx
- src/layouts/RegularLayout/RegularAppbar/index.tsx
- src/modules/core/AdminLoginButton/index.tsx
- src/modules/core/ConnectionButton/index.tsx
- yarn.lock
What does PR do?
- Login with useWallet with onConnect of useAccount
> Refactor: Login with useWallet with new version

- .gitignore
- Dockerfile
- docker-compose.yml
- src/components/EmptyData/index.tsx
- src/components/GLogo/index.tsx
- src/config/configuration.ts
- src/hooks/useOnLogin.ts
- src/layouts/DashboardLayout/index.tsx
- src/modules/AdminNft/ButtonBulkCreateModal/BulkNftForm/index.tsx
- src/modules/AdminWelcome/index.tsx
- src/modules/UserCollection/index.tsx
- src/modules/Welcome/index.tsx
- src/modules/core/ButtonAuthWalletModal/AuthWallet/index.tsx
- src/pages/_app.tsx
- src/utils/request.ts
- Refactor redirect when login admin/user
- Change brand name
_(notes)_
> Refactor: Change brand name and refactor redirect route

- src/contracts/cep78/index.ts
- src/enums/deployStatus.enum.ts
- src/enums/index.ts
- src/hooks/mutations/useMutateCreateNft.ts
- src/hooks/queries/useGetAdminNfts.ts
- src/hooks/queries/useGetAllNftCollections.ts
- src/modules/AdminNft/AdminNftTable/index.tsx
- src/modules/AdminNft/ButtonCreateModal/NftForm/index.tsx
- src/services/admin/nft/types.ts
- src/types/nft.ts
- src/utils/casper/contract.ts
- src/utils/status.ts
- Users don't need to wait to mint NFT
- Auto fetching NFT deploy status with API
_(notes)_
> Feat: Display deploy status and auto-fetch

- src/enums/deployStatus.enum.ts
- src/enums/mutationKeys.enum.ts
- src/hooks/mutations/index.ts
- src/hooks/mutations/useMutateCreateNftCollection.ts
- src/hooks/mutations/useMutateRegisterTokenOwner.ts
- src/modules/AdminNftCollection/AdminNftCollectionTable/ButtonRegisterTokenOwner/index.tsx
- src/modules/AdminNftCollection/AdminNftCollectionTable/ButtonRegisterTokenOwner/styled.tsx
- src/modules/AdminNftCollection/AdminNftCollectionTable/index.tsx
- src/services/admin/nft-collection/index.ts
- src/services/admin/nft-collection/types.ts
- src/types/nft-collection.ts
- src/utils/casper/account.ts
- src/utils/casper/contract.ts
- https://github.com/VK-Lab/mlem-dashboard/issues/13
- Create NFT Collection not waiting for transaction success
- Add register button
_(notes)_
> Feat: Create NFT Collection not waiting transaction

- .github/workflows/build.yml
- docker-compose.yml
> Refactor: Docker compose

- .github/workflows/build_deploy.yml
- .vscode/settings.json
- src/components/EmptyData/index.tsx
- CI Deploy and restart docker compose
> CI: Deploy Testnet on remote ssh

- src/config/configuration.ts
- src/enums/mutationKeys.enum.ts
- src/enums/paths.enum.ts
- src/enums/queryKeys.enum.ts
- src/hooks/mutations/index.ts
- src/hooks/mutations/useMutateCreateBenefitCategory.ts
- src/hooks/queries/index.ts
- src/hooks/queries/useGetAdminBenefitCategories.ts
- src/layouts/DashboardLayout/AdminSidebar/index.tsx
- src/modules/AdminBenefit/ButtonCreateModal/index.tsx
- src/modules/AdminBenefitCategory/AdminBenefitCategoryTable/index.tsx
- src/modules/AdminBenefitCategory/ButtonCreateModal/index.tsx
- src/modules/AdminBenefitCategory/ButtonCreateModal/styled.tsx
- src/modules/AdminBenefitCategory/index.tsx
- src/modules/UserNFTDetail/ListBenefits/index.tsx
- src/pages/admin/benefit-categories/index.tsx
- src/services/admin/benefit-category/index.ts
- src/services/admin/benefit-category/types.ts
- src/types/benefit-category.d.ts
- src/types/benefit.ts
- src/types/nft.ts
- yarn.lock
> Feat: Category for benefits

- src/modules/AdminNft/ButtonCreateModal/index.tsx
- src/modules/AdminNftCollection/AdminNftCollectionTable/ButtonRegisterTokenOwner/index.tsx
- #27 
- Show confirm popup before register token owner
_(notes)_
> Feat: Show confirm popup before register token owner

- src/config/configuration.ts
- src/contracts/cep78/index.ts
- src/contracts/cep78/types.ts
- src/hooks/mutations/useMutateCreateNftCollection.ts
- src/modules/AdminNft/ButtonCreateModal/NftForm/index.tsx
- src/modules/AdminNftCollection/AdminNftCollectionTable/index.tsx
- src/services/admin/nft/types.ts
- src/types/nft-collection.ts
- src/utils/casper/contract.ts
> Refactor: Remove register token

- .github/workflows/build_deploy.yml
- Dockerfile
> Build: DockerFile with alpine

- src/config/configuration.ts
> Refactor: Production env config

- .gitignore
- src/config/configuration.ts
> Release: 1.1.0

- next.config.js
- src/enums/nftType.enum.ts
- src/hooks/mutations/useMutateCreateNft.ts
- src/modules/AdminNft/ButtonCreateModal/NftForm/index.tsx
- src/services/admin/nft/index.ts
- src/services/admin/nft/types.ts
- src/services/proxy/index.ts
- src/services/wallet/index.ts
- src/utils/casper/contract.ts
- src/utils/metadata.ts
- #43 
- Refactor flow to mint token
> Refactor: #43 Change token uri format

- src/modules/AdminTiers/AdminTierTable/ButtonUpdateModal/index.tsx
- src/modules/AdminTiers/AdminTierTable/index.tsx
- src/modules/AdminTiers/ButtonCreateModal/TierForm/index.tsx
- src/services/admin/tier/types.ts
- src/types/tier.ts
> Feat: Add tier for slug

- package.json
- src/modules/AdminNftCollection/AdminNftCollectionTable/index.tsx
- src/modules/AdminTiers/AdminTierTable/index.tsx
- yarn.lock
> Feat: Display benefits for tier

- src/modules/UserNFTDetail/index.tsx
- src/types/nft.ts
- Add optional for tier
_(notes)_
> Fix: Undefined tier

- src/config/configuration.ts
- Update metadata base url
-
_(notes)_
> Refactor: Update metadata base url

- public/locales/en/common.json
- public/locales/vi/common.json
- src/modules/AdminNft/ButtonCreateModal/NftForm/index.tsx
- src/modules/AdminNftCollection/AdminNftCollectionTable/ButtonRegisterTokenOwner/index.tsx
- src/modules/AdminNftCollection/ButtonCreateModal/NftForm/index.tsx
- src/modules/AdminTiers/AdminTierTable/ButtonRegisterTokenOwner/index.tsx
- src/modules/UserNFTDetail/ListBenefits/index.tsx
> Fix: Typo and allow copy coupon code

- package.json
- src/components/Link/index.tsx
- src/hocs/RouterGuard.tsx
- src/modules/UserCollection/ListNfts/index.tsx
- src/modules/UserNFTDetail/index.tsx
- src/pages/_app.tsx
- src/theme/base/globals.ts
- yarn.lock
> Feat: Add nProgress bar

- package.json
- packages/admin/src/modules/AdminCampaign/AdminCampaignTable/ButtonUpdateModal/index.tsx
- packages/admin/src/modules/AdminCampaign/ButtonCreateModal/CampaignForm/index.tsx
- packages/admin/src/services/admin/campaign/types.ts
- packages/admin/src/types/campaign.ts
> Feat: Allow admin define thumbnail url

- packages/admin/package.json
- packages/admin/src/pages/_app.tsx
- packages/user/src/app/providers.tsx
- packages/user/src/modules/core/nft-minter/button-mint.tsx
- Turn off auto-connect In admin site
> Refactor: Turn off auto connect in admin

- .github/workflows/build_deploy_admin.yml
- .github/workflows/build_deploy_dev.yml
- packages/admin/Dockerfile
- packages/admin/node_modules/@casperdash/usewallet
- packages/admin/node_modules/@casperdash/usewallet-core
- packages/admin/tsconfig.json
- packages/user/.env.production
- packages/user/Dockerfile
- packages/user/package.json
- packages/user/tsconfig.json
- pnpm-lock.yaml
> CI: Deploy new structure to testnet

- packages/user/next.config.js
- packages/user/package.json
- packages/user/src/lib/format.ts
- packages/user/src/modules/user/user-header/index.tsx
- packages/user/src/services/casperdash/user/hooks/useGetAccountBalance.ts
- packages/user/src/services/casperdash/user/index.ts
- packages/user/src/services/casperdash/user/type.ts
- packages/user/src/services/casperdash/user/user.service.ts
- pnpm-lock.yaml
> Refactor: Turn off light mode

- .github/workflows/check.yml
- package.json
- packages/admin/package.json
> CI: Build and lint

- packages/user/src/app/globals.css
- packages/user/src/modules/campaign/campaign-detail/WhiteListForm.tsx
- packages/user/src/modules/campaign/campaign-detail/index.tsx
> UPDATE: - Fix left align content

- packages/admin/src/modules/AdminCampaign/AdminCampaignTable/ButtonUpdateModal/index.tsx
- packages/admin/src/services/admin/campaign/types.ts
- packages/admin/src/types/campaign.ts
- packages/user/src/modules/@core/nft-minter/index.tsx
- packages/user/src/modules/campaign/campaign-detail/index.tsx
- packages/user/src/services/app/campaign/hooks/useCheckUserInWhiteList.ts
- packages/user/src/services/app/campaign/index.tsx
- packages/user/src/services/app/campaign/types.ts
- packages/user/src/types/campaign.ts
- packages/user/src/types/nft-collection.ts
> Release: 1.3.10
